---

- name: update apt cache
  apt: update_cache=yes

- name: ensure apt works with https
  apt: name=apt-transport-https state=present

- name: ensure CA certificates are installed
  apt: name=ca-certificates state=present

- name: Ensure bridge-utils is installed
  apt: name=bridge-utils state=present

- name: install build-essential
  apt: name=build-essential update_cache=yes

- name: add the new GPG key for docker
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80 id=58118E89F3A912897C070ADBF76221572C52609D

- name: Copy the Docker list config for apt
  copy: src=templates/docker.list dest=/etc/apt/sources.list.d/docker.list

- name: Remove existing old lxc-docker repo
  apt: name=lxc-docker state=absent

- name: check kernel version
  shell: uname -r
  register: uname_result 

- name: install linux-image-extra-virtual package
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - linux-image-extra-{{ uname_result.stdout }}
    - linux-image-extra-virtual

- name: Ensure docker-engine is installed
  apt: name=docker-engine state=present update_cache=yes

- name: Restart docker service
  service: name=docker state=restarted
  tags:
    - dockerproxy 
